id: ID85C9700
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T14:11:27+00:00'
last_modified: '2022-06-07T10:39:09.683097+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5786
  title: ནི་གུའི་ཆོས་དྲུག་གྲུབ་པའི་དགོངས་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2DD4:
      image_group_id: I1KG5822
      title: Volume 1 of ni gu'i chos drug grub pa'i dgongs rgyan
      total_pages: 312
      order: 1
      base_file: 2DD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
